modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/plan-player-analytics/Plan/issues"

[[mods]]
modId="plan"
version="${version}"
displayName="Plan"
displayURL="https://github.com/plan-player-analytics/Plan"
authors="AuroraLS3, Player Analytics contributors"
description='''
Player Analytics plugin for NeoForge (via Forgified Fabric API).
'''

[[mixins]]
config="plan.mixins.json"

[[dependencies.plan]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.plan]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.plan]]
modId="fabric_api"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"
