name: Plan
author: AuroraLS3
main: com.djrapitops.plan.Plan
version: ${version}
api-version: 1.13
folia-supported: true
softdepend:
  - AAC
  - ASkyBlock
  - AdvancedAchievements
  - AdvancedBan
  - AuthMe
  - BanManager
  - BentoBox
  - CoreProtect
  - DiscordSRV
  - DKCoins
  - DKBans
  - Essentials
  - CMI
  - Factions
  - FastLogin
  - GriefPrevention
  - GriefPreventionPlus
  - Jobs
  - Kingdoms
  - LiteBans
  - LogBlock
  - LuckPerms
  - MarriageMaster
  - mcMMO
  - MinigamesLib
  - MyPet
  - nuVotifier
  - PlaceholderAPI
  - ProtectionStones
  - ProtocolSupport
  - Quests
  - React
  - RedProtect
  - SuperbVote
  - Towny
  - Vault
  - ViaVersion
  - Votifier

commands:
  plan:
    usage: /plan
    permission: plan.command

permissions:
  plan.command:
    default: true
  plan.server:
    default: op
  plan.servers:
    default: op
  plan.network:
    default: op
  plan.player.self:
    default: true
  plan.player.other:
    default: op
  plan.search:
    default: op
  plan.ingame.self:
    default: true
  plan.ingame.other:
    default: op
  plan.register.self:
    default: true
  plan.register.other:
    default: op
  plan.unregister.self:
    default: true
  plan.unregister.other:
    default: op
  plan.logout.other:
    default: op
  plan.info:
    default: op
  plan.reload:
    default: op
  plan.disable:
    default: op
  plan.users:
    default: op
  plan.data.base:
    default: op
  plan.data.backup:
    default: op
  plan.data.restore:
    default: op
  plan.data.move:
    default: op
  plan.data.hotswap:
    default: op
  plan.data.clear:
    default: op
  plan.data.remove.player:
    default: op
  plan.data.remove.server:
    default: op
  plan.data.export:
    default: op
  plan.data.import:
    default: op
  plan.json.self:
    default: true
  plan.json.other:
    default: op
  plan.ignore.commanduse:
    default: false
  plan.ignore.afk:
    default: false
